# -*- coding: utf-8 -*-
"""WineQuality_White.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLWOA4dtTbWWGtcGLpxkD7dbAi0t7kKy

#Wine quality prediction(Classification)

##Objective

To predict wine quality using classification models.

Design Decisions

- The original quality scores are regrouped into three categories:
    -  Low (≤5)

    -  Medium (=6)

    -  High (≥7)

-  Red and white wines are analysed separately.

-  At least three classification models are compared.

-  Evaluation metrics are selected based on classification performance.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

"""##Load White Wine Dataset"""

from google.colab import files
files.upload()

"""##Dataset description (White wine)
Features are physicochemical properties (e.g., acidity, sugar, chlorides).

Target is the original quality score (integer).

We convert it into a 3-class label for classification.
"""

WHITE_PATH = "data/winequality-white.csv"

white = pd.read_csv(WHITE_PATH, sep=';')

print("White wine dataset shape:", white.shape)
print(white.head())
print(white.describe())

def regroup_quality(q):
  if q <= 5:
    return "Low"
  elif q == 6:
    return "Medium"
  else:
    return "High"

white['quality_label'] = white["quality"].apply(regroup_quality)



print("Original quality distribution:")
print(white['quality'].value_counts().sort_index())

print("\nRegrouped label distribution:")
print(white['quality_label'].value_counts())

print("\nRegrouped label distribution(percentage):")
print(white['quality_label'].value_counts(normalize=True)*100)

"""##Data Balance
From the regroup quality label we can tell that it is imbalance but not too extreme.
"""

#split the data to train 80%   test 20%
X = white.drop(['quality','quality_label'] ,axis =1)
y = white['quality_label']
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state =42,
    stratify = y
    )

print(f"Train shape : {X_train.shape},{y_train.shape}")
print(f"Test shape : {X_test.shape},{y_test.shape}")

"""##Models

1.Logistic Regression : linear classifier baseline

2.Random forest : non-linear ensemble model

3.Multilayer perceptron : non-linear neural model

"""

#scaling for Logistic regression and mlp
scale = StandardScaler()
X_train_scaled =scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

#logistic regression
log_reg = LogisticRegression(max_iter=1000)

#Random Forest
forest = RandomForestClassifier(n_estimators=100,
                                  max_depth = None,
                                  random_state = 42
                                  )
#Multilayer perceptron
mlp = MLPClassifier(hidden_layer_sizes= (64,32),
                    activation = "relu",
                    solver = "adam",
                    max_iter= 1000,
                    random_state=42
                    )

"""##Evaluation metrics
-  Accuracy: overall correctness
-  Precision/Recall/F1: class-wise performance (important under imbalance)
-  Confusion Matrix: shows where misclassifications occur

"""

def evaluation ():
  names = []
  accs = []

  models = {
      "Logistic Regression" : (log_reg,True),
      "Random Forest" : (forest,False),
      "Multilayer Perceptron" : (mlp,True)
  }

  for name, (model,needs_scaling) in models.items():

    if needs_scaling:
      Xtr = X_train_scaled
      Xte = X_test_scaled
    else:
            Xtr = X_train
            Xte = X_test

    model.fit(Xtr,y_train)
    y_pred = model.predict(Xte)


    print(f"======Model : {name}  White wine ==========")
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy:", acc)
    print(classification_report(y_test, y_pred))
    disp = ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
    plt.title(name)
    plt.show()
    names.append(name)
    accs.append(acc)



  plt.figure()
  plt.bar(names, accs)
  plt.ylabel("Accuracy")
  plt.title("Accuracy Comparison")
  for i, v in enumerate(accs):
      plt.text(i, v, f"{v:.2f}", ha="center")

evaluation()

"""##Balance Confirmation
From the evaluation we conclude that the imbalance did not affect the model too much.
Because :
-  the macro average and weighted average is similar
-  the minority class('high') is not ignored (the recall is not low)
-   Performance is relatively balanced (no strong biased)

##Discussion
-  The regrouping converts the original integer quality scores into 3 categories, enabling a clearer classification task.
-  Logistic Regression provides a strong linear baseline
-  Random Forest typically performs best when relationships are non-linear.
-  Multilayer Perception provides nonlinear neural model

The confusion matrices and class-wise precision/recall/F1 explain which quality categories are most commonly confused.
"""
