# -*- coding: utf-8 -*-
"""WineQuality_RED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEiKOP8VyqgLQWcIZwfymbtKdFGo_OQ4

# Wine Quality Prediction (Classification)

## Objective
To predict wine quality using classification models.

## Design Decisions
- The original quality scores are regrouped into three categories:
  - Low (≤5)
  - Medium (=6)
  - High (≥7)
- Red and white wines are analysed separately.
- At least three classification models are compared.
- Evaluation metrics are selected based on classification performance.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

"""## Load Red Wine Dataset"""

RED_PATH = "data/winequality-red.csv"

red = pd.read_csv(RED_PATH, sep=';')

print("Red wine dataset shape:", red.shape)
print(red.head())
print(red.describe())

"""## Dataset description (Red wine)
Features are physicochemical properties (e.g., acidity, sugar, chlorides).

Target is the original `quality` score (integer).  

We convert it into a 3-class label for classification.
"""

def regroup_quality(q):
    if q <= 5:
        return "Low"
    elif q == 6:
        return "Medium"
    else:
        return "High"

red["quality_label"] = red["quality"].apply(regroup_quality)

print("Original quality distribution:")
print(red["quality"].value_counts().sort_index())

print("\nRegrouped label distribution:")
print(red["quality_label"].value_counts())

"""The dataset shows moderate class imbalance, particularly in the "High" quality category (≈14%).
Since no additional red wine dataset is available, we interpret model performance carefully using class-wise precision, recall and F1-score rather than relying solely on accuracy.

## Spilt dataset
"""

X = red.drop(columns=["quality", "quality_label"])
y = red["quality_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape: ", X_test.shape, y_test.shape)

"""## Models (3 models as required)
1. **GaussianNB**: baseline Naïve Bayes classifier.
2. **Logistic Regression**: linear classifier baseline.
3. **Random Forest**: non-linear ensemble model.

## Evaluation metrics (chosen for classification)
- Accuracy: overall correctness
- Precision/Recall/F1: class-wise performance (important under imbalance)
- Confusion Matrix: shows where misclassifications occur
"""

def evaluate_model(model, model_name, X_train, X_test, y_train, y_test, title_suffix="Red Wine"):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    print(f"\n=== {model_name} ({title_suffix}) ===")
    print("Accuracy:", acc)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred, labels=np.unique(y_test))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=np.unique(y_test))
    disp.plot(values_format="d")
    plt.title(f"Confusion Matrix - {model_name} ({title_suffix})")
    plt.show()

    return acc

"""### Logistic Regression Convergence Handling

Logistic Regression initially produced a convergence warning due to the difference in feature scales and limited iteration count.

To ensure proper optimization:
- Features were standardized using StandardScaler.
- The maximum number of iterations was increased to 3000.
- The lbfgs solver was used for stable multi-class optimization.

This guarantees that the model reaches convergence before evaluation.
"""

results = {}

results["GaussianNB"] = evaluate_model(
    GaussianNB(),
    "GaussianNB",
    X_train, X_test, y_train, y_test
)

# Logistic Regression with scaling to ensure convergence
log_reg = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=3000,
        solver="lbfgs",
        random_state=42
    ))
])

results["LogisticRegression"] = evaluate_model(
    log_reg,
    "Logistic Regression (Scaled)",
    X_train, X_test, y_train, y_test
)

results["RandomForest"] = evaluate_model(
    RandomForestClassifier(n_estimators=300, random_state=42),
    "Random Forest",
    X_train, X_test, y_train, y_test
)

print("\nAccuracy Summary:", results)

plt.figure()
plt.bar(list(results.keys()), list(results.values()))
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison (Red Wine)")
plt.show()

"""## Discussion (brief)

- The regrouping converts the original integer quality scores into 3 categories, enabling a clearer classification task.
- GaussianNB provides a simple probabilistic baseline.
- Logistic Regression provides a strong linear baseline.
- Random Forest typically performs best when relationships are non-linear.

The confusion matrices and class-wise precision/recall/F1 explain which quality categories are most commonly confused.
"""
